package com.qiwi.springboot;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import com.qiwi.springboot.Agent;
import com.qiwi.springboot.AgentRepository;

/**
 * Created by etrofimov on 18.07.17.
 */

public class AgentService {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AgentRepository agentRepository;


    static boolean isRightLogin(String login) {
        if (login.length() > 11) {
            return false;
        }
        for (int i = 0; i < login.length(); i++) {
            if (!Character.isDigit(login.charAt(i))) return false;
        }
        return true;
    }

    static boolean isLoginExists(String login) {
        if ((login != null) && (login.length() > 0)) return true;
        return false;
    }

    static boolean isPasswordExists(String password) {
        if ((password != null) && (password.length() > 0)) return true;
        return false;
    }

    Status registerNewAgent(AgentRequest agentRequest) {
        String login = agentRequest.getLogin();
        if (!isLoginExists(login) || !isRightLogin(login)) {
            return Status.WRONG_FORMAT;
        }

        String password = agentRequest.getPassword();
        if (!isPasswordExists(password) || (password.length() < 8) || (password.length() > 20)) {
            return Status.BAD_PASSWORD;
        }

        Agent agent = new Agent();
        agent.setTelephone(agentRequest.getLogin());
        agent.setPwd(agentRequest.getPassword());
        agentRepository.save(agent);
        return Status.OK;

    }

    Response getBalance(AgentRequest agentRequest) {
        String login = agentRequest.getLogin();
        if (!isLoginExists(login) || !isRightLogin(login)) {
            return new Response(Status.WRONG_FORMAT);
        }

        String password = agentRequest.getPassword();
        if (!isPasswordExists(password)) {
            return new Response(Status.BAD_PASSWORD);
        }

        return new Response(Status.OK);

//        return ClientDaoSingleton.getInstance().getUserBalance(agentRequest);
    }
}
