package com.qiwi.springboot;

/**
 * Created by etrofimov on 18.07.17.
 */
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import com.qiwi.springboot.Agent;
import com.qiwi.springboot.AgentRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AgentRepository agentRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewAgent (@RequestBody AgentRequest agentRequest) {

        Agent n = new Agent();
        n.setTelephone(agentRequest.getLogin());
        n.setPwd(HashCodeGenerator.getHashCode(agentRequest.getPassword()));
        agentRepository.save(n);
        return "Saved";
    }

}